[package]
authors = ["sponges <spongybacon@hotmail.co.uk>", "Zeyla Hellyer <zey@zey.moe>"]
description = "Rust client for Lavalink."
documentation = "https://docs.rs/lavalink"
homepage = "https://github.com/serenity-rs/lavalink.rs"
keywords = ["lavalink"]
license = "ISC"
name = "lavalink"
readme = "README.md"
repository = "https://github.com/serenity-rs/lavalink.rs.git"
version = "0.1.0"

[dependencies]
hyper = "~0.10"
log = "~0.4"
parking_lot = "^0.5"
percent-encoding = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"

[dependencies.evzht9h3nznqzwl]
default-features = false
features = ["sync-ssl"]
version = "0.0.3"
